spring:
  config:
    import: optional:file:.env.prod[.properties]
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?${MYSQL_SSL_PARAMS:useSSL=true&requireSSL=true&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
